### ISSUE TITLE
#solved

### ISSUE THREAD

**Issue by shahid-ullah** [maateen/awesome-vimrc#1]
I have faced the two problems.  My vim version 8.0

1. YouCompleteMe unavailable: requires Vim compiled with Python (2.7 or 3.4+) support.
Press ENTER or type command to continue
2. Error detected while processing function jedi#init_python:
line    7:
Error: jedi-vim failed to initialize Python: jedi-vim requires Vim with support 
for Python 2 or 3. (in function jedi#init_python[3]..<SNR>69_init_python, line 5
2)
Error: jedi-vim failed to initialize Python: jedi-vim requires Vim with support 
for Python 2 or 3. (in function jedi#init_python[3]..<SNR>69_init_python, line 5
2)
Press ENTER or type command to continue

**Comment by maateen** [comment]
What's your operating system? How have you installed VIM?

**Comment by shahid-ullah** [comment]
আপনার সম্পূর্ন নিয়ম ফলো করছিলাম। এখন ওইটা রিমোভ করো vim-gtk ইন্সটল দেওয়ার পর ঠিক আছে। আগের vim এ পাইথন সার্পোট করত না। আমি উবুন্টু 16.04 LTS  ব্যাবহার করতেছি।

**Comment by maateen** [comment]
I have recommended installing `vim-gnome` along with VIM. I think you have missed that.

**Comment by shahid-ullah** [comment]
Now how can I fully remove vim & install as new?
